"""Tests for the file parsing primitive (Step 1 of the media foundation).

Each test builds a real binary file via the format's own writer library
(python-docx, openpyxl, python-pptx, pypdf), POSTs it to /files/parse,
and asserts a markdown sidecar comes back.
"""

from __future__ import annotations

import os

import pytest

from main import app


@pytest.fixture()
def parsing_client(client, tmp_path):
    files_dir = str(tmp_path / "files")
    parsed_dir = os.path.join(files_dir, "_parsed")
    os.makedirs(parsed_dir, exist_ok=True)
    app.state.files_dir = files_dir
    app.state.parsed_files_dir = parsed_dir
    return client


def _write_docx(path: str) -> None:
    from docx import Document

    doc = Document()
    doc.add_heading("Estructura del Documento", level=1)
    doc.add_paragraph("Esta es una guía estructural.")
    doc.add_heading("Sección 1", level=2)
    doc.add_paragraph("Contenido de la primera sección.")
    table = doc.add_table(rows=2, cols=2)
    table.rows[0].cells[0].text = "Encabezado A"
    table.rows[0].cells[1].text = "Encabezado B"
    table.rows[1].cells[0].text = "valor 1"
    table.rows[1].cells[1].text = "valor 2"
    doc.save(path)


def _write_xlsx(path: str) -> None:
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.title = "Datos"
    ws.append(["nombre", "valor"])
    ws.append(["alpha", 1])
    ws.append(["beta", 2])
    wb.save(path)


def _write_pptx(path: str) -> None:
    from pptx import Presentation

    pres = Presentation()
    blank = pres.slide_layouts[6]
    slide = pres.slides.add_slide(blank)
    box = slide.shapes.add_textbox(0, 0, 9144000, 6858000)
    tf = box.text_frame
    tf.text = "Título de la diapositiva"
    p2 = tf.add_paragraph()
    p2.text = "Punto importante"
    pres.save(path)


def _write_pdf(path: str) -> None:
    # pypdf can write a minimal PDF, but the simpler route is to round-trip a
    # one-page PDF generated by a tiny helper. We use pypdf's PdfWriter to add
    # a blank page and then inject text via a content stream — overkill for a
    # smoke test. Instead we emit a minimal valid PDF by hand.
    pdf_bytes = (
        b"%PDF-1.4\n"
        b"1 0 obj <</Type /Catalog /Pages 2 0 R>> endobj\n"
        b"2 0 obj <</Type /Pages /Kids [3 0 R] /Count 1>> endobj\n"
        b"3 0 obj <</Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R "
        b"/Resources <</Font <</F1 5 0 R>>>>>> endobj\n"
        b"4 0 obj <</Length 44>> stream\n"
        b"BT /F1 24 Tf 100 700 Td (Hola PDF) Tj ET\n"
        b"endstream endobj\n"
        b"5 0 obj <</Type /Font /Subtype /Type1 /BaseFont /Helvetica>> endobj\n"
        b"xref\n0 6\n0000000000 65535 f\n"
        b"0000000010 00000 n\n0000000053 00000 n\n"
        b"0000000100 00000 n\n0000000206 00000 n\n0000000295 00000 n\n"
        b"trailer <</Size 6 /Root 1 0 R>>\nstartxref\n360\n%%EOF\n"
    )
    with open(path, "wb") as f:
        f.write(pdf_bytes)


def test_capabilities(parsing_client):
    res = parsing_client.get("/files/capabilities")
    assert res.status_code == 200
    body = res.json()
    assert set(body["supported_extensions"]) >= {"docx", "xlsx", "pptx", "pdf"}
    assert body["max_parsed_chars_per_file"] > 0


def test_parse_docx_returns_markdown_sidecar(parsing_client, tmp_path):
    src = tmp_path / "estructura.docx"
    _write_docx(str(src))

    res = parsing_client.post("/files/parse", json={"file_path": str(src)})
    assert res.status_code == 200, res.text
    body = res.json()
    assert body["parsed_path"].endswith(".md")
    assert body["parser"] == "python-docx"
    assert body["char_count"] > 0
    assert os.path.exists(body["parsed_path"])
    with open(body["parsed_path"], encoding="utf-8") as f:
        text = f.read()
    assert "# Estructura del Documento" in text
    assert "## Sección 1" in text
    assert "| Encabezado A | Encabezado B |" in text
    assert "| valor 1 | valor 2 |" in text


def test_parse_docx_cache_hit(parsing_client, tmp_path):
    src = tmp_path / "estructura.docx"
    _write_docx(str(src))
    a = parsing_client.post("/files/parse", json={"file_path": str(src)}).json()
    b = parsing_client.post("/files/parse", json={"file_path": str(src)}).json()
    assert a["sha256"] == b["sha256"]
    assert b["cached"] is True
    assert a["parsed_path"] == b["parsed_path"]


def test_parse_xlsx(parsing_client, tmp_path):
    src = tmp_path / "datos.xlsx"
    _write_xlsx(str(src))
    res = parsing_client.post("/files/parse", json={"file_path": str(src)})
    assert res.status_code == 200, res.text
    body = res.json()
    assert body["parser"] == "openpyxl"
    with open(body["parsed_path"], encoding="utf-8") as f:
        text = f.read()
    assert "## Sheet: Datos" in text
    assert "| nombre | valor |" in text
    assert "| alpha | 1 |" in text


def test_parse_pptx(parsing_client, tmp_path):
    src = tmp_path / "slides.pptx"
    _write_pptx(str(src))
    res = parsing_client.post("/files/parse", json={"file_path": str(src)})
    assert res.status_code == 200, res.text
    body = res.json()
    assert body["parser"] == "python-pptx"
    with open(body["parsed_path"], encoding="utf-8") as f:
        text = f.read()
    assert "## Slide 1" in text
    assert "Título de la diapositiva" in text
    assert "Punto importante" in text


def test_parse_pdf(parsing_client, tmp_path):
    src = tmp_path / "doc.pdf"
    _write_pdf(str(src))
    res = parsing_client.post("/files/parse", json={"file_path": str(src)})
    assert res.status_code == 200, res.text
    body = res.json()
    assert body["parser"] == "pypdf"
    with open(body["parsed_path"], encoding="utf-8") as f:
        text = f.read()
    assert "Hola PDF" in text


def test_parse_unsupported_returns_422(parsing_client, tmp_path):
    src = tmp_path / "song.mp3"
    src.write_bytes(b"ID3 fake bytes")
    res = parsing_client.post("/files/parse", json={"file_path": str(src)})
    assert res.status_code == 422
    assert "Unsupported" in res.text


def test_parse_missing_returns_404(parsing_client):
    res = parsing_client.post(
        "/files/parse", json={"file_path": "/nonexistent/path.docx"}
    )
    assert res.status_code == 404


def test_parse_batch(parsing_client, tmp_path):
    docx_path = tmp_path / "a.docx"
    xlsx_path = tmp_path / "b.xlsx"
    bad_path = tmp_path / "missing.pdf"
    _write_docx(str(docx_path))
    _write_xlsx(str(xlsx_path))
    res = parsing_client.post(
        "/files/parse/batch",
        json={
            "files": [
                {"file_path": str(docx_path)},
                {"file_path": str(xlsx_path)},
                {"file_path": str(bad_path)},
            ]
        },
    )
    assert res.status_code == 200, res.text
    items = res.json()["items"]
    assert items[0]["ok"] is True
    assert items[1]["ok"] is True
    assert items[2]["ok"] is False
    assert "not found" in items[2]["error"]


def test_get_parsed_by_sha(parsing_client, tmp_path):
    src = tmp_path / "estructura.docx"
    _write_docx(str(src))
    parsed = parsing_client.post("/files/parse", json={"file_path": str(src)}).json()
    sha = parsed["sha256"]

    res = parsing_client.get(f"/files/parsed/{sha}")
    assert res.status_code == 200
    body = res.json()
    assert body is not None
    assert body["sha256"] == sha
    assert body["cached"] is True

    miss = parsing_client.get("/files/parsed/" + "0" * 64)
    assert miss.status_code == 200
    assert miss.json() is None


def test_from_path_registers_file_item_with_sniffed_mime(parsing_client, tmp_path):
    src = tmp_path / "estructura.docx"
    _write_docx(str(src))
    res = parsing_client.post(
        "/files/items/from-path",
        json={"file_path": str(src), "source": "chat-upload"},
    )
    assert res.status_code == 201, res.text
    body = res.json()
    assert body["sha256"] is not None and len(body["sha256"]) == 64
    assert body["mime"] == (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    assert body["storage_kind"] == "workspace"
    assert body["storage_path"] == str(src)
    assert body["source"] == "chat-upload"

    # Re-register same path → de-dupes by (sha, path, source).
    res2 = parsing_client.post(
        "/files/items/from-path",
        json={"file_path": str(src), "source": "chat-upload"},
    )
    assert res2.status_code == 201
    assert res2.json()["id"] == body["id"]


def test_from_path_rejects_invalid_source(parsing_client, tmp_path):
    src = tmp_path / "x.docx"
    _write_docx(str(src))
    res = parsing_client.post(
        "/files/items/from-path",
        json={"file_path": str(src), "source": "definitely-not-allowed"},
    )
    assert res.status_code == 400
