/**
 * Expert avatar catalog.
 *
 * Stored expert avatars reference an `id` (e.g. `"guide-dog"`). The id is
 * stable across the app's lifetime — never bundle PNGs by importing them
 * here. Instead we render the unicode emoji char in a span styled with
 * the bundled Twemoji font (see `app.css`), giving identical visuals on
 * Mac/Windows/Linux at ~470 KB total cost (the font itself).
 *
 * The id → emoji mapping is auto-generated by
 * `scripts/generate-avatar-mapping.mjs` from `src/assets/avatars/*.png`
 * filenames — re-run that script if the avatar set changes.
 */

import { GENERATED_AVATAR_OPTIONS } from './avatars.generated';

export interface AvatarOption {
  id: string;
  label: string;
  emoji: string;
  keywords: string[];
  group: string;
}

export const AVATAR_OPTIONS: AvatarOption[] = [...GENERATED_AVATAR_OPTIONS].sort(
  (a, b) => a.label.localeCompare(b.label),
);

const byId = new Map(AVATAR_OPTIONS.map((a) => [a.id, a]));

export function getAvatar(id: string | null | undefined): AvatarOption | null {
  if (!id) return null;
  return byId.get(id) ?? null;
}
